/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_bd.view;

import crud_bd.classes.AlphabeticalOrderPeople;
import crud_bd.classes.Person;
import crud_bd.dao.PersonDAO;
import crud_bd.table.TabelModel;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class InternalScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalScreen
     */
    private final PersonDAO pD = new PersonDAO();
    private TabelModel modelo;
    private final String REGEX;
    private Person personControll;
    
    public InternalScreen(String regex) {
        initComponents();
        this.REGEX = regex;
        modelo = new TabelModel();
        alterar_tabela.setModel(modelo);
        alterar_btn_enviar.setEnabled(false);
        try {
            List<Person> list = pD.returnAllPeople();
            Collections.sort(list, new AlphabeticalOrderPeople());
            for(Person aux: list) modelo.addPerson(aux);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    public void clear () {
        alterar_in_email.setText("");
        alterar_in_nome.setText("");
        alterar_in_telefone.setText("");
        alterar_in_idade.setText("");
        alterar_btn_enviar.setEnabled(false);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alterar_tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alterar_btn_alterar = new javax.swing.JButton();
        alterar_btn_enviar = new javax.swing.JButton();
        alterar_btn_cancelar = new javax.swing.JButton();
        alterar_in_telefone = new javax.swing.JFormattedTextField();
        alterar_in_nome = new javax.swing.JTextField();
        alterar_in_email = new javax.swing.JTextField();
        alterar_in_idade = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(79, 79, 79));

        alterar_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(alterar_tabela);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Idade");

        alterar_btn_alterar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        alterar_btn_alterar.setText("Alterar");
        alterar_btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btn_alterarActionPerformed(evt);
            }
        });

        alterar_btn_enviar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        alterar_btn_enviar.setText("Enviar");
        alterar_btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btn_enviarActionPerformed(evt);
            }
        });

        alterar_btn_cancelar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        alterar_btn_cancelar.setText("Cancelar");
        alterar_btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btn_cancelarActionPerformed(evt);
            }
        });

        try {
            alterar_in_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alterar_in_nome)
                                    .addComponent(alterar_in_email)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterar_in_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterar_in_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alterar_btn_alterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alterar_btn_enviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alterar_btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alterar_btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(alterar_in_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(alterar_btn_enviar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(alterar_in_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alterar_in_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alterar_btn_cancelar)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(alterar_in_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterar_btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btn_alterarActionPerformed
       
        int index = alterar_tabela.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um morador para realizar esta operação");
            return;
        }
        alterar_btn_enviar.setEnabled(true);
        
        personControll = modelo.getPersonIndex(index);
        alterar_in_nome.setText(personControll.getName());
        alterar_in_email.setText(personControll.getEmail().equals("null")? "" : personControll.getEmail());
        alterar_in_telefone.setText(personControll.getPhoneNumber());
        alterar_in_idade.setText(Integer.toString(personControll.getAge()));
    }//GEN-LAST:event_alterar_btn_alterarActionPerformed

    private void alterar_btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_alterar_btn_cancelarActionPerformed

    private void alterar_btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btn_enviarActionPerformed
        
        String nome = alterar_in_nome.getText();
        if(nome.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, informe um nome");
            return;
        }
        
        String email = alterar_in_email.getText();
        if(email.equals("")) email = "null";
        else if(!email.matches(REGEX)){
            JOptionPane.showMessageDialog(null, "Por favor, informe um e-mail válido");
            return;
        }
        
        String telefone = alterar_in_telefone.getText();
        if(telefone.equals("(  ) 9    -    ")) telefone = "null";
        
        Integer idade = null;
        try {
            idade = Integer.parseInt(alterar_in_idade.getText());
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Por favor, informe uma idade válida");
        }
        
        Person p = new Person(nome.trim(), email, telefone, idade);
        p.setId_person(personControll.getId_person());
        
        if(p.equals(personControll)){
            JOptionPane.showMessageDialog(null, "Não houve alteração dos dados do morador");
            clear();
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja atualizar os dados?", 
                "Confirmação de atualização", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            try {
                pD.updatePerson(p);
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
                dispose();
                clear();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
            }
        } else {
            clear();
        }
        
    }//GEN-LAST:event_alterar_btn_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar_btn_alterar;
    private javax.swing.JButton alterar_btn_cancelar;
    private javax.swing.JButton alterar_btn_enviar;
    private javax.swing.JTextField alterar_in_email;
    private javax.swing.JTextField alterar_in_idade;
    private javax.swing.JTextField alterar_in_nome;
    private javax.swing.JFormattedTextField alterar_in_telefone;
    private javax.swing.JTable alterar_tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
