/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_bd.view;

import crud_bd.classes.Car;
import crud_bd.classes.Person;
import crud_bd.dao.CarDAO;
import crud_bd.dao.CascadeExclusionDAO;
import crud_bd.dao.InnerJoinDAO;
import crud_bd.dao.PersonDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javaapplication2.JTextFieldHint;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    private final String EXC_SQL = "Ocorreu algum erro no banco de dados";
    private final String REGEX = "([\\w-\\.])+@([a-zA-Z])+(\\.([a-zA-Z])+){1,}";
    private boolean cadCar;     // true para cadastro, false para alteração
    private Integer cadCar_id_foreign;
    private Integer cadCar_id_car;

    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        cadCarSetEnable(false, new Color(103,42,114));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        painel_fundo_principal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        in_nome = new JTextFieldHint(new JTextField(), "", "Nome completo do morador");
        jLabel2 = new javax.swing.JLabel();
        in_email = new JTextFieldHint(new JTextField(), "", "E-mail para contato");
        jLabel3 = new javax.swing.JLabel();
        in_telefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        in_idade = new JTextFieldHint(new JTextField(), "", "Idade");
        btn_enviar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cadCar_nomeBusca = new JTextFieldHint(new JTextField(), "", "Nome completo para pesquisa");
        cadCar_btn_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cadCar_in_modelo = new JTextFieldHint(new JTextField(), "", "Modelo do carro");
        cadCar_in_marca = new JTextFieldHint(new JTextField(), "", "Marca do carro");
        cadCar_in_cor = new JTextFieldHint(new JTextField(), "", "Cor do carro");
        cadCar_in_placa = new JTextFieldHint(new JTextField(), "", "Placa do carro");
        cadCar_btn_enviar = new javax.swing.JButton();
        cadCar_btn_cancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 7, 67));

        painel_fundo_principal.setBackground(new java.awt.Color(18, 7, 67));

        jTabbedPane1.setBackground(new java.awt.Color(18, 7, 67));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));

        jLabel1.setBackground(new java.awt.Color(153, 0, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome completo");

        in_nome.setBackground(new java.awt.Color(141, 53, 226));
        in_nome.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_nome.setForeground(new java.awt.Color(255, 255, 255));
        in_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");

        in_email.setBackground(new java.awt.Color(141, 53, 226));
        in_email.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_email.setForeground(new java.awt.Color(255, 255, 255));
        in_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone");

        in_telefone.setBackground(new java.awt.Color(141, 53, 226));
        in_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        in_telefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            in_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        in_telefone.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        in_telefone.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Idade");

        in_idade.setBackground(new java.awt.Color(141, 53, 226));
        in_idade.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_idade.setForeground(new java.awt.Color(255, 255, 255));
        in_idade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_enviar.setBackground(new java.awt.Color(72, 61, 139));
        btn_enviar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Enviar");
        btn_enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_enviarMouseExited(evt);
            }
        });
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(72, 61, 139));
        btn_cancelar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar/limpar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(in_nome)
                            .addComponent(in_email)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(in_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(in_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_email, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(in_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Cadastro de moradores", jPanel1);

        jPanel2.setBackground(new java.awt.Color(18, 7, 67));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome do morador");

        cadCar_nomeBusca.setBackground(new java.awt.Color(141, 53, 226));
        cadCar_nomeBusca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_nomeBusca.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_nomeBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadCar_btn_buscar.setBackground(new java.awt.Color(72, 61, 139));
        cadCar_btn_buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_btn_buscar.setText("Buscar");
        cadCar_btn_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));
        cadCar_btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCar_btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadCar_btn_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadCar_btn_buscarMouseExited(evt);
            }
        });
        cadCar_btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCar_btn_buscarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(18, 7, 67));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226)));
        jPanel3.setInheritsPopupMenu(true);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Placa");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cor");

        cadCar_in_modelo.setBackground(new java.awt.Color(141, 53, 226));
        cadCar_in_modelo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_in_modelo.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_in_modelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadCar_in_marca.setBackground(new java.awt.Color(141, 53, 226));
        cadCar_in_marca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_in_marca.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_in_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadCar_in_cor.setBackground(new java.awt.Color(141, 53, 226));
        cadCar_in_cor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_in_cor.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_in_cor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadCar_in_placa.setBackground(new java.awt.Color(141, 53, 226));
        cadCar_in_placa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_in_placa.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_in_placa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadCar_btn_enviar.setBackground(new java.awt.Color(72, 61, 139));
        cadCar_btn_enviar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_btn_enviar.setText("Enviar");
        cadCar_btn_enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));
        cadCar_btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCar_btn_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadCar_btn_enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadCar_btn_enviarMouseExited(evt);
            }
        });
        cadCar_btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCar_btn_enviarActionPerformed(evt);
            }
        });

        cadCar_btn_cancelar.setBackground(new java.awt.Color(72, 61, 139));
        cadCar_btn_cancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cadCar_btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cadCar_btn_cancelar.setText("Cancelar/limpar");
        cadCar_btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 53, 226), 2));
        cadCar_btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCar_btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadCar_btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadCar_btn_cancelarMouseExited(evt);
            }
        });
        cadCar_btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCar_btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadCar_in_modelo)
                            .addComponent(cadCar_in_marca)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cadCar_in_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cadCar_in_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cadCar_btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadCar_btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCar_in_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCar_in_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadCar_in_placa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadCar_in_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCar_btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCar_btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadCar_nomeBusca)
                        .addGap(18, 18, 18)
                        .addComponent(cadCar_btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cadCar_nomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCar_btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Cadastro e alteração de carros", jPanel2);

        javax.swing.GroupLayout painel_fundo_principalLayout = new javax.swing.GroupLayout(painel_fundo_principal);
        painel_fundo_principal.setLayout(painel_fundo_principalLayout);
        painel_fundo_principalLayout.setHorizontalGroup(
            painel_fundo_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundo_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        painel_fundo_principalLayout.setVerticalGroup(
            painel_fundo_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundo_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(painel_fundo_principal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Moradores");

        jMenuItem1.setText("Alterar dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Excluir usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carros");

        jMenuItem3.setText("Excluir carro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearInput() {
        in_nome.setText("");
        in_email.setText("");
        in_idade.setText("");
        in_telefone.setText("");
    }

    public void clearCadCar() {
        cadCar_in_modelo.setText("");
        cadCar_in_cor.setText("");
        cadCar_in_marca.setText("");
        cadCar_in_placa.setText("");
        cadCar_nomeBusca.setText("");
    }
    
    public void cadCarSetEnable(boolean b, Color background) {
        cadCar_in_cor.setEnabled(b);
        cadCar_in_marca.setEnabled(b);
        cadCar_in_modelo.setEnabled(b);
        cadCar_in_placa.setEnabled(b);
        cadCar_btn_enviar.setEnabled(b);
        cadCar_btn_cancelar.setEnabled(b);
        cadCar_in_cor.setBackground(background);
        cadCar_in_marca.setBackground(background);
        cadCar_in_modelo.setBackground(background);
        cadCar_in_placa.setBackground(background);
    }

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed

        String name = in_nome.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe um nome");
            return;
        }

        String email = in_email.getText();
        if (email.equals("")) email = "null";
        else if (!email.matches(REGEX)) {
            JOptionPane.showMessageDialog(null, "Por favor, informe um e-mail válido");
            return;
        }

        String telefone = in_telefone.getText();
        if (telefone.equals("(  ) 9    -    ")) {
            telefone = "null";
        }

        Integer idade = null;
        try {
            idade = Integer.parseInt(in_idade.getText());
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Por favor, informe uma idade válida");
        }

        Person p = new Person(name.trim(), email, telefone, idade);
        PersonDAO pD = new PersonDAO();

        try {
            pD.addPerson(p);
            JOptionPane.showMessageDialog(null, "Morador cadastrado com sucesso!");
            clearInput();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, EXC_SQL);
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        clearInput();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    public void mouseEnteredEnviar(JButton btn) {
        btn.setBorder(new javax.swing.border.LineBorder(Color.WHITE, 2, true));
        btn.setBackground(Color.GREEN);
    }

    public void mouseEnteredCancelar(JButton btn) {
        btn.setBorder(new javax.swing.border.LineBorder(Color.WHITE, 2, true));
        btn.setBackground(Color.RED);
    }

    public void mouseExited(JButton btn) {
        btn.setBackground(new Color(72, 61, 139));
        btn.setBorder(new javax.swing.border.LineBorder(new Color(141, 53, 226), 2, true));
    }


    private void btn_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enviarMouseEntered
        mouseEnteredEnviar(btn_enviar);
    }//GEN-LAST:event_btn_enviarMouseEntered

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        mouseEnteredCancelar(btn_cancelar);
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void btn_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enviarMouseExited
        mouseExited(btn_enviar);
    }//GEN-LAST:event_btn_enviarMouseExited

    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        mouseExited(btn_cancelar);
    }//GEN-LAST:event_btn_cancelarMouseExited

    private void cadCar_btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCar_btn_buscarActionPerformed
        String nome = cadCar_nomeBusca.getText();
        if (nome.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, informe um nome para busca");
            return;
        }
        
        List<Person> list = null;
        Person p = null;
        
        try {
            list = new PersonDAO().returnAllPeople();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, EXC_SQL);
        }
        
        for(Person aux: list) if(aux.getName().equals(nome)) p = aux;
        if (p != null){
            
            cadCar_id_foreign = p.getId_person();
            String out = "Usuário(a) encontrado(a)!\n\n";
            out += "Nome: "+p.getName()+"\n";
            out += (p.getEmail().equals("null") ? "" : "E-mail: "+p.getEmail()+"\n");
            out += (p.getPhoneNumber().equals("null") ? "" : "Telefone "+p.getPhoneNumber()+"\n");
            out += "Idade: "+p.getAge()+"\n\n";
            out += "O resultado da busca está correto?"; 
            int resposta = JOptionPane.showConfirmDialog(null, out, "Confirmação de busca", JOptionPane.YES_NO_OPTION);
            
            if (resposta == JOptionPane.YES_OPTION){
                Car c = null;
                try {
                    c = new CarDAO().carSearch(p.getId_person());
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, EXC_SQL);
                }
                
                if (c != null){
                    String output = "O usuário possui um ou mais carros cadastrados\n";
                    output += "Deseja alterar os dados de algum registro existente?\n\n";
                    output += "Caso deseje realizar um novo cadastro, nega esta confirmação";
                    int resp = JOptionPane.showConfirmDialog(null, output, "Confirmação de alteração", JOptionPane.YES_NO_OPTION);
                    cadCarSetEnable(true, new Color(141, 53, 226));
                    
                    if(resp == JOptionPane.NO_OPTION) { cadCar = true; }
                    else {
                        cadCar = false;
                        Object[] outp = null;
                        try {
                            outp = new CarDAO().returnAllCars(true, p.getId_person()).toArray();
                        } catch (SQLException e1) {
                            e1.printStackTrace();
                            JOptionPane.showMessageDialog(null, EXC_SQL);
                        }
                        Car alterar =  (Car) JOptionPane.showInputDialog(null, "Selecione o veículo desejado",
                                "Alteração", JOptionPane.QUESTION_MESSAGE, null, outp, outp[0]);
                        
                        cadCar_id_car = alterar.getId_car();
                        cadCar_in_cor.setText(alterar.getColor());
                        cadCar_in_modelo.setText(alterar.getModel());
                        cadCar_in_marca.setText(alterar.getBrand());
                        cadCar_in_placa.setText(alterar.getLicensePlate());
                    }
                } else {
                    cadCarSetEnable(true, new Color(141, 53, 226));
                    cadCar = true;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, considere letras maiúsculas e minúsculas e tente novamente");
                clearCadCar();
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            clearCadCar();
        }
    }//GEN-LAST:event_cadCar_btn_buscarActionPerformed

    private void cadCar_btn_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_buscarMouseEntered
        mouseEnteredEnviar(cadCar_btn_buscar);
    }//GEN-LAST:event_cadCar_btn_buscarMouseEntered

    private void cadCar_btn_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_buscarMouseExited
        mouseExited(cadCar_btn_buscar);
    }//GEN-LAST:event_cadCar_btn_buscarMouseExited

    private void cadCar_btn_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_enviarMouseEntered
        mouseEnteredEnviar(cadCar_btn_enviar);
    }//GEN-LAST:event_cadCar_btn_enviarMouseEntered

    private void cadCar_btn_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_enviarMouseExited
        mouseExited(cadCar_btn_enviar);
    }//GEN-LAST:event_cadCar_btn_enviarMouseExited

    private void cadCar_btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_cancelarMouseEntered
        mouseEnteredCancelar(cadCar_btn_cancelar);
    }//GEN-LAST:event_cadCar_btn_cancelarMouseEntered

    private void cadCar_btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCar_btn_cancelarMouseExited
        mouseExited(cadCar_btn_cancelar);
    }//GEN-LAST:event_cadCar_btn_cancelarMouseExited

    private void cadCar_btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCar_btn_cancelarActionPerformed
        clearCadCar();
        cadCarSetEnable(false, new Color(103,42,114));
    }//GEN-LAST:event_cadCar_btn_cancelarActionPerformed

    private void cadCar_btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCar_btn_enviarActionPerformed
        
        Car c;
        String modelo = cadCar_in_modelo.getText();
        String marca = cadCar_in_marca.getText();
        String cor = cadCar_in_cor.getText();
        String placa = cadCar_in_placa.getText().toUpperCase();

        if(modelo.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, informe o modelo do veículo");
            return;
        }

        if(placa.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, informe a placa do veículo");
            return;
        }
            
        c = new Car(modelo, marca, placa, cor);
        c.setId_foreign(cadCar_id_foreign);
        c.setId_car(cadCar_id_car);
        CarDAO cD = new CarDAO();
        
        if(cadCar){
            try {
                cD.addCar(c);
                JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!");
            } catch (SQLException e1) {
                e1.printStackTrace();
                JOptionPane.showMessageDialog(null, EXC_SQL);
            }
        } else {
            try {
                cD.updateCar(c);
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
            } catch (SQLException e1) {
                e1.printStackTrace();
                JOptionPane.showMessageDialog(null, EXC_SQL);
            }
        }
        
        clearCadCar();
        cadCarSetEnable(false, new Color(103,42,114));
        
    }//GEN-LAST:event_cadCar_btn_enviarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        String placa = JOptionPane.showInputDialog(null, "Informe a placa do veículo");
        if(placa == null) return;
        
        Car c = null;
        Person p = null;
        CarDAO cD = new CarDAO();
        try {
            for(Car aux: cD.returnAllCars(false, -1))
                if(aux.getLicensePlate().equals(placa.toUpperCase())) c = aux;
            if(c != null) p = new PersonDAO().personSearch(c.getId_foreign());
            else {
                JOptionPane.showMessageDialog(null, "Veículo não encontrado");
                return;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, EXC_SQL);
        }
        
        String out = "Veículo encontrado\n\n";
        out += "Modelo: '"+c.getModel()+"' - "+c.getBrand()+" ("+c.getColor()+")\n\n";
        out += "Informações do proprietário\n";
        out += "Nome: "+p.getName()+"\n";
        out += (p.getEmail().equals("null")? "" : p.getEmail())+"\n";
        out += (p.getPhoneNumber().equals("null")? "" : p.getPhoneNumber())+"\n\n";
        out += "Você tem certeza que deseja excluir este veículo?";
        
        int resposta = JOptionPane.showConfirmDialog(null, out, "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try {
                cD.deleteCar(c.getId_car());
                JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!");
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, EXC_SQL);
            }
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        String nome = JOptionPane.showInputDialog(null, "Informe o nome do morador");
        if(nome == null) return;
        
        Person p = null;
        List<Car> list = null;
        PersonDAO pD = new PersonDAO();
        try {
            for(Person aux : pD.returnAllPeople())
                if(aux.getName().equals(nome)) p = aux;
            if(p == null) {
                JOptionPane.showMessageDialog(null, "Morador não encontrado");
                return;
            }
            list = new ArrayList<>();
            list = InnerJoinDAO.allCars(p.getId_person(), pD.getConnection());
        } catch(SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, EXC_SQL);
        }
        
        String out = "Morador encontrado\n\n";
        if(list != null){
            out += (list.size()==1?"O morador possui um carro cadastrado: ":"O morador possui os seguintes carros cadastrados:")+"\n";
            for(Car c: list){
                out += "Modelo: '"+c.getModel()+"' - "+c.getBrand()+" ("+c.getColor()+")\n";
                out += "Placa: "+c.getLicensePlate()+"\n\n";
            }
            out += "Ao excluir um morador, os carros cadastrados em seu nome também serão excluídos.\n";
        }
        out += "Você tem certeza que deseja realizar esta operação?\n";

        int resposta = JOptionPane.showConfirmDialog(null, out, "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            try{
                CascadeExclusionDAO.cascadeExclusion(p.getId_person(), pD.getConnection());
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
            } catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, EXC_SQL);
            }
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InternalScreen telaAlterar = new InternalScreen(REGEX);
        jDesktopPane1.add(telaAlterar);
        telaAlterar.setVisible(true);
        telaAlterar.setPosicao();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton cadCar_btn_buscar;
    private javax.swing.JButton cadCar_btn_cancelar;
    private javax.swing.JButton cadCar_btn_enviar;
    private javax.swing.JTextField cadCar_in_cor;
    private javax.swing.JTextField cadCar_in_marca;
    private javax.swing.JTextField cadCar_in_modelo;
    private javax.swing.JTextField cadCar_in_placa;
    private javax.swing.JTextField cadCar_nomeBusca;
    private javax.swing.JTextField in_email;
    private javax.swing.JTextField in_idade;
    private javax.swing.JTextField in_nome;
    private javax.swing.JFormattedTextField in_telefone;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painel_fundo_principal;
    // End of variables declaration//GEN-END:variables
}
